INSERT INTO [lkpDepartment] VALUES('放射科								', NULL, 1 , 1)
INSERT INTO [lkpDepartment] VALUES('急诊儿科							', NULL, 2 , 2)
INSERT INTO [lkpDepartment] VALUES('普通儿科							', NULL, 3 , 2)
INSERT INTO [lkpDepartment] VALUES('呼吸、消化内科						', NULL, 4 , 2)
INSERT INTO [lkpDepartment] VALUES('心血管内科							', NULL, 5 , 2)
INSERT INTO [lkpDepartment] VALUES('肾内、风湿、免疫内科				', NULL, 6 , 2)
INSERT INTO [lkpDepartment] VALUES('新生儿科							', NULL, 7 , 2)
INSERT INTO [lkpDepartment] VALUES('重症医学科							', NULL, 8 , 2)
INSERT INTO [lkpDepartment] VALUES('妇科								', NULL, 9 , 2)
INSERT INTO [lkpDepartment] VALUES('产科								', NULL, 10, 2)
INSERT INTO [lkpDepartment] VALUES('内分泌、代谢、血液、肿瘤内科		', NULL, 11, 2)
INSERT INTO [lkpDepartment] VALUES('五官科								', NULL, 12, 2)
INSERT INTO [lkpDepartment] VALUES('神经内科							', NULL, 13, 2)
INSERT INTO [lkpDepartment] VALUES('骨科								', NULL, 14, 2)
INSERT INTO [lkpDepartment] VALUES('神经、胸、泌尿、烧伤外科			', NULL, 15, 2)
INSERT INTO [lkpDepartment] VALUES('普外科								', NULL, 16, 2)
INSERT INTO [lkpDepartment] VALUES('感染科								', NULL, 17, 2)
INSERT INTO [lkpDepartment] VALUES('检验科								', NULL, 18, 1)
INSERT INTO [lkpDepartment] VALUES('麻醉手术室							', NULL, 19, 1)
INSERT INTO [lkpDepartment] VALUES('供应室								', NULL, 20, 9)
INSERT INTO [lkpDepartment] VALUES('健康管理中心						', NULL, 21, 9)
INSERT INTO [lkpDepartment] VALUES('临床检验中心						', NULL, 22, 1)
INSERT INTO [lkpDepartment] VALUES('血液净化中心						', NULL, 23, 1)
INSERT INTO [lkpDepartment] VALUES('病理科								', NULL, 24, 1)
INSERT INTO [lkpDepartment] VALUES('介入中心							', NULL, 25, 2)
INSERT INTO [lkpDepartment] VALUES('内窥镜室							', NULL, 26, 1)
INSERT INTO [lkpDepartment] VALUES('高压氧治疗中心						', NULL, 27, 1)
INSERT INTO [lkpDepartment] VALUES('心电检查中心						', NULL, 28, 1)
INSERT INTO [lkpDepartment] VALUES('超声影像中心						', NULL, 29, 1)
INSERT INTO [lkpDepartment] VALUES('阴道镜室							', NULL, 30, 9)
INSERT INTO [lkpDepartment] VALUES('门诊妇科手术室						', NULL, 31, 2)
INSERT INTO [lkpDepartment] VALUES('门诊化验室							', NULL, 32, 9)
INSERT INTO [lkpDepartment] VALUES('供血科								', NULL, 33, 9)
INSERT INTO [lkpDepartment] VALUES('碎石科								', NULL, 34, 9)
INSERT INTO [lkpDepartment] VALUES('急诊科								', NULL, 35, 2)
INSERT INTO [lkpDepartment] VALUES('口腔科								', NULL, 36, 2)
INSERT INTO [lkpDepartment] VALUES('产房								', NULL, 37, 2)