-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgBczzVYscxcVHebeD
vz/hAokrrDd36N8itScdib/d79GgCgYIKoZIzj0DAQehRANCAAQlBGq5/2nQrgFR
NxgjfnuIO4kGOBPkrV5uzWwbqqDTV/dVVuVFYFfVmWn7/djpZYW4VlJzreDrzS8X
Pk6Ibko6
-----END PRIVATE KEY-----